
#═══════[ CORE CONFIG ]═══════✧#
SESSION_ID='BWM-XMD;;;H4sIAAAAAAAAA5VU25KiSBD9l3rVGBFE0IiOWEQQvHQ7It429qGAAopLFRYFihP++wR29/REzOxsL09FUmSec/JkfgOE4hItUAPG30DBcA05ao+8KRAYg0kVhoiBLgggh2AMyueVN88F2wojvzxoR2MnO8+37bVZRvFS3sCh7tmqIuQHIjyBexcUlZdh/w8JA0F+uUgVjhitZ50BD6dBMiBXNnMUMY7jnlT3C5zusj6xn8C9zQgxwyQyihjliMFsgZo1xOxz8P1JP706s6XYGJcFO56xWaeLF09viGKeo84kDcvZes9v2135Ofh5OOXnU+G6xOqd9n3UmxuCukxhnu02e/k8KVNkUUxOL8Yb/BJHBAV2gAjHvPm07rkW7SOS326LU5iY1WppusVE3PewwlUSHdeeGfv8KieKZH8OuKoGG+8so2HmirFhulzi7PT1KNnL+fPJwNaC7ciJasIiXf0MfM3evZL+H92NFb0dD/JeNDfN4VrOQyZAyajoyM+dqTgMy54qzymZCkL0OfjLgxNkhIvePE6jwKmkSzwvFCf2B6XKj+sdfL5o3kI+ZwfjAz7kFfsTSkWkXkAL62jSiXfaLVeW0DHPnaDmiaz0p/uXZSbU03S+jtCus8nkQ1oczgnGzlGoD5sqp1sk8aWgG9nVshf6s0BGTnR5ejBKUWMHYNy/dwFDES45gxxT0sZGwy6AQe0gnyH+UBeQDdU0gdimhzruUmHT+tBYyjZTRkIwsDyynR1vqmSf3Xr1BLqgYNRHZYkCC5ecsmaFyhJGqATjvx+NajkzlFOO5jgAYyDKQ0URhZEgKvJf5ZdLDHkJi+ILQRx0QchovkJgzFmFuuDxw1QWxb4pTQxlJMnmSBEGU3PQ19SpqE+1kWq0DPPXoluco5LDvADjviILQ0EVh+L9ny4g6Mpf7dOSlvpdEGJWcpdURUZh8O6t94/Q92lFuNMQX28PiIGx8BFGnGMSlS2zikDmx7hGessDjEOYleiHzoih4J3L2+7QadC2f7PeGOJkOAIt9jbRL9qMxcGv8mSPa5I4UvtDcSANBEUS24tt/P4DYJsvQBzirARjoM/r9RWVM2O9dQYrezbT7EjTIw18EHr356sBvCrZW4qT5AryYZLLUnwgvRTv5plrIzPUlltiDYfXbd0cn36TpDXzqLB654lqDF/8QDPWk/X21rFU2VvGO2kmKSM55x3B2y4Nw+okunly2U5x5RObOhuaiE2mhlanJPv5alMvyORQxlmitWbuggDV2Ec/F7u8JM9Z3K/mi+3Ne7GPFfTqlUi9TaPOGlff71MHeWHz/FUqtLpJNqfpIG8idbHAnDcdV+nZbOGe58ltJc9GaLjnfqEk0evkPCY3e9uY+M3U+PEaYvRYQAS2Dfzv1r0Cbx0m3Ls/5Xhbaf+yFiZ7hfbjjkDlSiIzKlfBYCf3ZDtzTjvdig8XXZCvnap0FTUH99bqRQZ5SFkOxgCSgFEcgC5gtGota5OQ/qGYrkW28cY8gyXXPsbgN5MlS6+31owWFizjVoTZQMur1tONVhQOh/x9qoDWPpN0A+7fAekt5k/3BwAA'
PREFIX="."
PUBLIC_MODE='yes'

#═══════[ OWNER DETAILS ]═══════✧#
OWNER_NAME="Ibrahim adams 
OWNER_NUMBER="254"

#═══════[ BOT PROFILE ]═══════✧#
BOT_NAME="BWM-XMD"
BOT_IMAGE=""
STARTING_BOT_MESSAGE='yes'

#═══════[ PRESENCE & AUTOMATION ]═══════✧#
PRESENCE=''
AUTO_READ="no"
AUTO_READ_STATUS="yes"
AUTO_DOWNLOAD_STATUS="no"

#═══════[ CHAT FEATURES ]═══════✧#
CHATBOT="no"
AUDIO_CHATBOT="no"

#═══════[ GROUP SECURITY ]═══════✧#
GROUPANTILINK_REMOVE="no"
ANTIDELETE_SENT_INBOX="yes"
ANTIDELETE_RECOVER_CONVENTION="no"

#═══════[ MESSAGE HANDLING ]═══════✧#
STATUS_REACT_EMOJIS="🚀,🌎"
AUTO_REACT="no"
WELCOME_MESSAGE="no"
GOODBYE_MESSAGE="no"

#═══════[ HEROKU CONFIG ]═══════✧#
HEROKU_APP_NAME=
HEROKU_API_KEY=

#═══════[ AUTO REACTIONS ]═══════✧#
AUTO_REACT_STATUS="yes"
AUTO_REPLY_STATUS="no"
AUTO_REJECT_CALL="no"
AUTO_BIO="no"
#════════════════════════════✧#
